pipeline:
  docker:
    image: plugins/docker
    dockerfile: Dockerfile
    repo: foo/bar
    registry: docker-registry.test.abm-inventory.app
    auto_tag: true
  #backend:
  #  image: docker-registry.test.abm-inventory.app/base-images:latest
  #  commands:
  #    - ls -la
  #    - whoami
  #    - yum upgrade -y
