pipeline:
  docker:
    image: plugins/docker
    dockerfile: Dockerfile
  #backend:
  #  image: docker-registry.test.abm-inventory.app/base-images:latest
  #  commands:
  #    - ls -la
  #    - whoami
  #    - yum upgrade -y
