pipeline:
  docker:
    image: plugins/docker
    dockerfile: Dockerfile
    repo: registry.abm-inventory.app/test/app
    registry: registry.abm-inventory.app
    secrets: [ docker_username, docker_password ]
    auto_tag: true
  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: drone
    when:
      status: [ success, failure ]
